### PR TITLE
Remove embedded keystone policy config change

### PR DESCRIPTION
**Pull request by andy-ning**
Currently keystone policy file (policy.json) is from a WRS custom file
patched into keystone source tree. This update removed the patched file
from keystone and instead use a puppet template to generate one at
system configuration time (puppet manifest apply).

Story: 2003110
Task: 23229

Signed-off-by: Andy Ning <andy.ning@windriver.com>

### CODE REVIEW

**Comment by andy-ning** [comment]
The changes to puppet manifest are in reviews:
https://review.openstack.org/#/c/594523/
https://review.openstack.org/#/c/594525/

**Comment by tliu88** [comment]
The change looks good.

**Comment by andy-ning** [comment]
Hi Dean, Please don't merge this commit until the other two commits to puppet manifest are merged, otherwise there will be no policy file for keystone.

**Comment by andy-ning** [comment]
Hi Dean, this commit can be merged since the other changes have passed review (at Gerrit) and been merged.

**Pull request merged**
